# HW1 - Covariance Matrix

**Covariance** is used to measure how two random variables change or vary together. For example, the height and weight of giraffes have a positive covariance because when one is big, the other tends to also be big.

_In this assignment, we will calculate the **covariance matrix** for a given dataset._

This assignment will consist of two parts:

## Part 1

**IMPORTANT NOTE:** in the video, the equation he uses has $n$ as the denominator, but when he calculates covariance values, he's using $n-1$ as the denominator. _For our purposes, we will be using $n-1$ as the denominator._

Watch this video on covariance matrices: https://www.youtube.com/watch?v=0GzMcUy7ZI0

Mathematically, we can represent Covariance as such:

$Cov(X,Y)=1/(n-1) \sum_{i=1}^{n}(x[i] - \bar{x})(y[i] - \bar{y})$

Where $n$ is the number of elements in arrays $x$ and $y$

## Part 2

Write a Python function that returns the covariance matrix for a given dataset, just like we watched in the video or any other dataset of your choosing. Below are various places you can get datasets from:

### Dataset Resources

- [Kaggle](https://www.kaggle.com/datasets)
- [Fivethirtyeight](https://github.com/fivethirtyeight/data)
- [Buzzfeed News](https://github.com/BuzzFeedNews/everything)
- [Google Cloud BigQuery Public Datasets](https://cloud.google.com/bigquery/public-data/)
- [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Database_download)
- Can't find anything from above? Google around until you do!

## Part 3

Use [numpy's var function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html) to confirm that the covariance between a variable and itself is the same as the variance of the variable.

For example, assuming your covariance function is named `cov`, ensure that the following is true: `cov(X, X) == np.var(X)`

### Hints

1. Obtain the covariance between columns $x$ and $y$, between columns $x$ and $z$, and columns $y$ and $z$
1. The covariance between columns $x$ and $y$ is the same as the covariance between columns $y$ and $x$. _We can generalize this for any two columns_
1. Show that the covariance between columns $x$ and $x$ is equal to the variance of column $x$. _We can generalize this for any other column_

## Testing Your Code

Verify your code with numpy built-in `np.cov()` function as follows:

In [80]:
import numpy as np

def cov_matrix_calculation(data):
    # calculate covariance matrix of the data
    cov_matx = np.cov(data.T)
    return cov_matx

dataset = np.array([[1, 1, 1], [1, 2, 1], [1, 3, 2], [1, 4, 3]])
print(cov_matrix_calculation(dataset))


[[0.         0.         0.        ]
 [0.         1.66666667 1.16666667]
 [0.         1.16666667 0.91666667]]


# Requirements

To pass this HW, you must meet the following requirements

1. Your function should return the covariance between 6 pairs of random variables: $(X,Y), (X, Z), (Y, Z), (X, X), (Y, Y), and (Z, Z)$
1. Verify that your function's return value is correct by using `np.cov(DATA)` where `DATA` is the return value of your covariance function
1. Verify that your covariance function for each variable with itself returns the same value as `np.var` of that variable

## Stretch Challenges

These are optional challenges for those who want to further expand their skillset:

1. Your function should display the covariance in a matrix format

In [131]:
import numpy as np
import pandas as pd

# df = pd.read_csv('drug-use-by-age.csv')
# print(df['age'])

# keep getting error that file is not found. I manually input the data.
# the 4 subjects are the ages: 12, 13, 14, 15
# x = alcohol use, y = marijuana use, z = cocaine use


def cov_matrix_calculation(data):
    cov_matrix = np.cov(data.T)
    cov_matrix_rounded = np.around(cov_matrix, decimals = 1)
    
    return cov_matrix_rounded


dataset_one = np.array([[3.9, 1.1, 0.1], [8.5, 3.4, 0.1], [18.1, 8.7, 0.1], [29.2, 14.5, 0.5]])
print("Matrix of data: \n" + str(dataset_one) + "\n")
print("Covariance: \n" + str(cov_matrix_calculation(dataset_one)) + "\n")

print("This is the x column: " + str(x_column)) # prints out the x column 

print("This is cov(x,x): " + str(cov_matrix_calculation(dataset_one)[0,0])) # prints out cov(x, x)
print("This is cov(y,y): " + str(cov_matrix_calculation(dataset_one)[1,1])) # prints out cov(y,y)
print("This is cov(z,z): " + str(cov_matrix_calculation(dataset_one)[2,2])) #prints out cov(z,z)

Matrix of data: 
[[ 3.9  1.1  0.1]
 [ 8.5  3.4  0.1]
 [18.1  8.7  0.1]
 [29.2 14.5  0.5]]

Covariance: 
[[125.6  66.9   1.9]
 [ 66.9  35.6   1. ]
 [  1.9   1.    0. ]]

This is the x column: [ 3.9  8.5 18.1 29.2]
This is cov(x,x): 125.6
This is cov(y,y): 35.6
This is cov(z,z): 0.0


In [109]:
twelve_yr_old = [3.9, 1.1, 0.1]
thirteen_yr_old = [8.5, 3.4, 0.1]
fourteen_yr_old = [18.1, 8.7, 0.1]
fifteen_yr_old = [29.2, 14.5, 0.5]

x = [3.9, 8.5, 18.1, 29.2]
y = [1.1, 3.4, 8.7, 14.5]
z = [0.1, 0.1, 0.1, 0.5]

x_mean = np.mean(x) # expected 14.925

x_var = np.var(x) # expected 125.6
y_var = np.var(y) # expected 35.6
z_var = np.var(z) # expected 


print(x_mean)
print(x_var)
print(y_var)
print(z_var)


# NOTE: I'm not sure why the variance is not being calculated correctly here. I did the calculations by hand
# they came out as expected, not as printed below. 

14.925
94.171875
26.721874999999997
0.03


## Turning In Your HW

Once you have finished your assignment, provide a link to your repo on GitHub and place the link in the appropriate `HW1` column in the [progress tracker](https://docs.google.com/spreadsheets/d/1bJ959aAhQbuJBA_vL1uinDgcEM6k7uROHLg_Wh5Ac2Y/edit?usp=sharing)